### ISSUE TITLE
update bot list

### ISSUE THREAD

**Issue by craigh** [zikula-modules/DizkusModule#259]
I'm not sure the bot list is at all useful at the moment. It is only utilized in two places in the controllers and the list is quite small.

if this is an effective means of preventing bots from crawling the site, then the list should be expanded - maybe pulled from a json file or remote source that stays up to date.

otherwise, the method should be abandoned entirely for some other method if desired.

**Comment by Guite** [comment]
I guess historically the list's purpose was to limit traffic specifically for the German support site.

**Comment by Kaik** [comment]
I'm removing it.
