### ISSUE TITLE
Unable to Set Custom Locale

### ISSUE THREAD

**Issue by shefik** [zikula-modules/DizkusModule#274]
I tested custom locale file in the following paths:

```
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.po
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.mo
```

or

```
/config/locale/en/LC_MESSAGES/module_dizkus.po
/config/locale/en/LC_MESSAGES/module_dizkus.mo
```

However, the custom text is not being loaded. What is the correct path to use for this module?

**Comment by shefik** [comment]
When I go to this URL:

```
/forums
```

Only the following "Search overrides" domains are loaded:

systemplugin_imagine
systemplugin_mapstraction
zikula

Line 550 of:

```
/lib/i18n/ZLanguage.php
```

**Comment by shefik** [comment]
Refs. https://github.com/zikula/core/issues/2407

**Comment by shefik** [comment]
I found out what the issue is. in Zikula 1.3.x, the path was something like:

```
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.po
/config/locale/en/LC_MESSAGES/module_zikuladizkusmodule.mo
```

But, in Zikula 1.4.0, the path is now:

```
/config/locale/en/LC_MESSAGES/zikuladizkusmodule.po
/config/locale/en/LC_MESSAGES/zikuladizkusmodule.mo
```

Using ```module_``` in the file name is no longer valid.

**Comment by shefik** [comment]
Also, another problem is at this example URL, where you would go to "Edit" the module. If you click "Restore", it incorrectly sets the module domain as:

```
module_dizkusmodule/zikula/module/dizkusmodule
```

When just this module domain is expected:

```
zikuladizkusmodule
```

As a result, the locale file is not able to be loaded, since the path is not correct.

**Comment by Guite** [comment]
@shefik is this fixed by https://github.com/zikula/core/pull/2408 ?

**Comment by shefik** [comment]
@Guite Yes, it is fixed. Closing ticket.
