### ISSUE TITLE
Zikula/Module/DizkusModule/Controller/UserController::ajax() does not exist

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/DizkusModule#276]
Hello Developers,

I have shown with Dizkus a problem and although I will that:

    Zikula/modules/DizkusModule/Controller/Controller User :: ajax () does not exist

This appears when I try to write a Quick Reply in Forum. Can you help me maybe and give a tip. Thank you in advance.

**Comment by craigh** [comment]
what version of the core and Dizkus are you using?

try reloading routes for Dizkus.

**Comment by AlexL777** [comment]
I use Zikula 1.4 RC and the last version of Dizkus. I have disabled the option "Enable user-side ajax" in the Settings of Dizkus and now I can edit topics and work with Quick Reply again. But why is this ajax option well?

**Comment by craigh** [comment]
> Zikula 1.4 RC

do you mean one of the RC versions posted at zikula.org or a current pull from github?

> last version of Dizkus

there is no 'last version'. do you mean a current pull from github?

> try reloading routes for Dizkus.

did you try this?

**Comment by AlexL777** [comment]
The Zikula 1.4 I have from this source: http://zikula.org/blog/display/2015/3/31/zikula-core-140-rc2-released

Dizkus version I have from this source: https://github.com/zikula-modules/DizkusModule

Very strange and I have just uploaded the controller directory again and then again the ajax option enabled in the Dizkus settings and posted in Forum Quick Reply. It works again.

But hm ... well then you can conclude that because it works again.

**Comment by craigh** [comment]
I find it more reliable to upload archive packages (.zip) and unpackage them at the server than to upload thousands of small files.
