### ISSUE TITLE
Error in quick reply

### ISSUE THREAD

**Issue by Guite** [zikula-modules/DizkusModule#277]
Got the following message when posting a quick reply @ zikula.org:

> Catchable Fatal Error: Argument 1 passed to Zikula\Module\DizkusModule\Entity\ForumUserEntity::removeTopicSubscription() must be an instance of Zikula\Module\DizkusModule\Entity\TopicSubscriptionEntity, null given, called in /.../modules/Dizkus/Zikula/Module/DizkusModule/Api/TopicApi.php on line 156 and defined

**Comment by craigh** [comment]
seems to work for me: http://zikula.org/forums/topic/59884#pid267902

what browser are you using? I just used safari.

**Comment by craigh** [comment]
second test with Chrome also worked.

**Comment by craigh** [comment]
deleted my tests to not pollute the thread.

**Comment by Guite** [comment]
Works fine.
