### ISSUE TITLE
Dizkus installation fail 

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/DizkusModule#279]
Hi,
I'm testing new zikula 1.4.1 with modules and Dizkus do not wan't to install due to Zikula\Module\UsersModule references there is many of them in the code I was able to partially get it to work but need to find all of them.
Hope to send here all the changes soon.

**Comment by craigh** [comment]
Yes. I guess that is expected given the changes in the core at 1.4.1. Dizkus is quite highly coupled to the core. Probably too much 😃

**Comment by pheski** [comment]
Also stuck here. Any idea about a time frame for this being fixed.  (NOT a request to rush - just want some info to help create better timelines for myself for what I work on next.)  Thanks.

**Comment by craigh** [comment]
are you working with the current repo? Didn't @Kaik 's changes fix the problem?

**Comment by craigh** [comment]
@pheski's error:
> The target-entity Zikula\\Module\\GroupsModule\\Entity\\GroupEntity cannot be found in 'Zikula\\Module\\DizkusModule\\Entity\\ModeratorGroupEntity#group'.

**Comment by craigh** [comment]
@pheski I don't think you were using a current pull from this repo. I've just updated it again, but the class you referenced had already been fixed. Please grab the latest pull and try again.

**Comment by pheski** [comment]
@craigh - I just now downloaded the most current version using the 'download zip' button. Same result. Does that not get me the current and most updated version?

**Comment by Kaik** [comment]
I think its cached somewhere or maybe git, check "clone into local github" step that current directory is in sync with current branch and current branch is current master.

**Comment by rallek** [comment]
@pheski I can install Dizkus in the given directory structure. I am using 1.4.1 final for the test.

**Comment by craigh** [comment]
@pheski - what's the status on this? If you are only updating the module by overwriting files you may have problems. You might try deleting the `app/cache/prod` directory and allowing it to rebuild. If that doesn't work, you may need to reinstall. Please let me know.

**Comment by pheski** [comment]
I apologize for the delay. My day job (family physician) tends to involve 12+ hours days and I have a 96 year old aunt who lives 2 hours away for whom I am the responsible caregiver….so I get to do my Zikula stuff in interrupted bursts…


1. I never update a module by overwriting.
2. I just installed a freshly acquired Dizqus on a fresh 1.4.1 with no problem.
3. In the next few days I will return to the site that was giving me a problem, uninstall, remove, and upload a fresh version.

Seems fixed to me.

Thanks. 

Peter

**Comment by pheski** [comment]
With a fresh Zikula 1.4.2 and a fresh zip downloaded from GIT here I get this error when I try to install:

The target-entity Zikula\Module\GroupsModule\Entity\GroupEntity cannot be found in 'Zikula\Module\DizkusModule\Entity\ModeratorGroupEntity#group'.

Looking back at the previous discussion, I deleted the app/cache/prod directory as suggested, and this time it fails with this error:

An exception occurred while executing 'INSERT INTO dizkus_forums (name, description, topicCount, postCount, forum_order, lvl, rgt, cat_id, pop3Connection, moduleref, status, parent, last_post_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["ROOT243fs546g1565h88u9fdjkh3tnbti8f2eo78f", "", 0, 0, null, null, null, null, "N;", 0, 1, null, null]: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'forum_order' cannot be null

**Comment by Guite** [comment]
Which MySQL version do you use?

**Comment by pheski** [comment]
5.6.25 based on a SQL select version () query.

Would/could this be related to InnoDB vs MyISAM? My host currently defaults to InnoDB which is what I am using, though I have the options of using MyISAM. The documentation in 1.4.2 does not address this that I can see.

Peter

**Comment by paustian** [comment]
I tried out 1.4.5 with Dizkus and am seeing this same error. I did a bit of snooping and it's when the example forums are added. I think there is an error in FormEntity, line 77. Here is the line.

 /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="forum_order", type="integer")
     */
    private $lft;

I think the code should be...

 /**
     * @Gedmo\TreeLeft
     * @ORM\Column(name="lft", type="integer")
     */
    private $lft;

**Comment by Kaik** [comment]
@paustian part of code you mentioned is ok.. please create a new issue with a full error description you are experiencing.
