### ISSUE TITLE
Can't edit title of thread I start when solved

### ISSUE THREAD

**Issue by pheski** [zikula-modules/DizkusModule#283]
Using the Dizkus forum on the Zikula site, I have tried to edit the title of threads I have started when the issue is resolved.  When I click on the title, I am able to make an edit and click submit, the edited title appears, but if I navigate away and return, the old title persists.

**Comment by pheski** [comment]
Appears to be fixed.

**Comment by craigh** [comment]
nobody changed anything ;-)
