### ISSUE TITLE
Refactor to PSR-4

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/DizkusModule#284]
I can start working on new version of Dizkus.
I think a first step would be to refactor to PSR-4
Then second #262 This would require refactoring to new Controller and Twig. I will start with admin controller and then step by step until smarty is removed completely. I prefer manual refactoring than automated.

@craigh I will contact you on slack so we can Diskus this :)

**Comment by craigh** [comment]
sounds good. go ahead

**Comment by Kaik** [comment]
Done
