### ISSUE TITLE
Api refactor

### ISSUE THREAD

**Issue by Kaik** [zikula-modules/DizkusModule#293]
We need to discuss files and functions new placement that are in Api directory.
AccountApi - LinkContainer
AdminApi - LinkContainer
BlockApi - ?
CronApi - ?
FavoritiesApi - ?
ForumApi - some functions are not needed smarty helpers, some can be replaced by Entity/Repository
ModeratorsApi - one funcion
NotifyApi - ?
ParseTagsApi - quote and code tags handler 
PermissionsApi - ?
PostApi - Repository - ?
PrefsApi -LinkContainer ?
RankApi - ?
SyncApi - ? service 
TopicApi - Entity/Repository - ?
UserApi - various -?
UserDataApi - ? on function.

Please look those files and let me know what you think @craigh @cmfcmf @Guite

**Comment by craigh** [comment]
API _means_ something that is useful *outside* this application - *intended* to be used outside the application. It seems unlikely that ANY of those functions are truly APIs.

Basically, they should all be moved to helper services or replaced by repository functions, etc. and the API tag/name must be removed it it really isn't an API. 😄

**Comment by Kaik** [comment]
I'm pretty sure that Api folder will go. I'm asking because you might have some good ideas where to put some of those. I bet I will ask you about some functions where to move it service-repo that is why I have created this issue to have, a place to discuss it :dancers:

**Comment by Kaik** [comment]
I need to spend some time to find a good place/replacement for each function. Will be back soon 3-4 days.

**Comment by Guite** [comment]
CronApi, FavouritesApi, NotifyApi, RankApi are probable candidates for services.

**Comment by craigh** [comment]
if it has no dependencies, it can just be a standalone class...

**Comment by Kaik** [comment]
Ok api s done and with it most of dizkus. I will back soon to finish what is left bit by bit...
