### ISSUE TITLE
DizkusModulInstaller Upgrade 3.1 - 4.0 - dizkus_users - wrong column name

### ISSUE THREAD

**Issue by lasker** [zikula-modules/DizkusModule#298]
Hello!

During the upgrade there is a column rename from user_rank to rank. But this rename is after the following two updates. 

`         $sql = "UPDATE dizkus_users SET rank=NULL WHERE rank=0";
        $stmt = $connection->prepare($sql);
        $stmt->execute();
        // set rank to NULL where rank no longer available
        $sql = "UPDATE dizkus_users set rank=NULL WHERE rank NOT IN (SELECT DISTINCT rank_id from dizkus_ranks)";
        $stmt = $connection->prepare($sql);
        $stmt->execute();
`

**Comment by Kaik** [comment]
This should be fixed in current master, I'm closing this issue now. Please create new issue if problem still exists.
