### ISSUE TITLE
Type error: Argument 1 passed to 

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/DizkusModule#303]
Hello Developers,

With Diskuz, there are smaller problems under Zikula 1.4.6 and I can not create forums. This error is displayed to me. Can you test with you and if necessary, the module fixed or update.

Thanks in advance.

`Type error: Argument 1 passed to Zikula\DizkusModule\Manager\ForumUserManager::__construct() must implement interface Zikula\Common\Translator\TranslatorInterface, integer given, called in /xxxxxxxxxxxxxxxxxxxxxx/liebrecht-projekte.de/httpdocs/cms/zikula/src/modules/zikula/diskuz-module/Entity/ForumEntity.php on line 423`

**Comment by Kaik** [comment]
Which version of Dizkus you are using?

**Comment by AlexL777** [comment]
I use the version 4.1.0, but now I work with it again quite well. Let's see if it will remain so.

**Comment by Kaik** [comment]
I'm closing this since many things have changed since. Please test current master and create new issue if problem still exists.
