### ISSUE TITLE
Uncaught Error: The route "zikuladizkusmodule_ajax_editpost" does not exist

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/DizkusModule#304]
Hello Developers,

I have here some issues to the Dizkus forum.

The editing of the topics does not work and the Chrome Inspector shows me that the route `"zikuladizkusmodule_ajax_editpost"` is non-existent.

Can you check and test this.

I use Zikula 1.4.6 and the last Diskuz version.

P.S. Routes in the backend I have none and even if I reload them. Since the list with the Routes is simply empty. Is this normal or something is wrong with the Routes?

**Comment by Kaik** [comment]
I'm closing this since current master does not support ajax at the moment and this will be addressed in future PR's. Mentioned route does not exist anymore and current javascript does not reflect those changes yet.
In other words, those types of errors are expected to occur at the moment.
