### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "zikuladizkusmodule_user_index" as such route does not exist.")

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/DizkusModule#305]
Hello Developers,

It is once that I want to use Zikula CMS. For this reason, I test and try out all the options in the backend and the modules.

All of a sudden, I have these error messages in the frontend after installing and setting up the Dizkus forum.

`Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "zikuladizkusmodule_user_index" as such route does not exist.").`

`in app/cache/prod/appProdDebugProjectContainerUrlGenerator.php at line 404   -
    public function generate($name, $parameters = array(), $referenceType = self::ABSOLUTE_PATH)
    {
        if (!isset(self::$declaredRoutes[$name])) {
            throw new RouteNotFoundException(sprintf('Unable to generate a URL for the named route "%s" as such route does not exist.', $name));
        }
        list($variables, $defaults, $requirements, $tokens, $hostTokens, $requiredSchemes) = self::$declaredRoutes[$name];`

Reloading the Routes did not help. The module version is the last one for Zikula 1.4.3 and higher. I am using Zikula 1.4.6.

Can you see this again.

Thanks in advance.

I uninstall the module until the problem is fixed.

**Comment by rallek** [comment]
@Kaik is currently rewriting this module and make it fit for the future. I am sure he will fix the problem.

**Comment by Kaik** [comment]
Hi, as @rallek mentioned Dizkus master is under refactor and current master is not usable.
You can use https://github.com/zikula-modules/DizkusModule/tree/4.0.0 which is last(the only) working version

I will resume work on Dizkus soon.

**Comment by Kaik** [comment]
I'm closing this since many things have changed since. Please test current master and create a new issue if the problem still exists.
