### ISSUE TITLE
500 Server Error when calling the settings at Dizkus Module

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/DizkusModule#318]
Hello Developers,

I just installed Zikula 2.0 and Dizkus 5.0. But unfortunately under the settings when calling the module settings comes a 500 server error.

What could be the problem.

In the general settings I see nowhere that one can activate permalinks. I am only the .htaccess file before, as it was and otherwise I have my installation under https://zikula15.wpzweinull.ch.

I hope you can help me.

Thanks in advance.

P.S. I have managed server with PHP 7.1 and MySQL 5.7.

**Comment by Kaik** [comment]
Please allow me few days and Dizkus 5.0 will be updated with current work. I have just merged work from not released 4.1 and need adjust few things.

**Comment by AlexL777** [comment]
Ok, thanks, no Problem. Another employment on the internet I have for me :)

**Comment by Kaik** [comment]
I have updated v5 and it should work now. Please confirm.

**Comment by AlexL777** [comment]
I have tried the Master Branch and v5 Branch in Zikula 2.0. The v5 shows this error during installation.

```
Fatal error: Uncaught Symfony\Component\Yaml\Exception\ParseException: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 355 (near "- [setForumUserService, [@zikula_dizkus_module.forum_user_manager]]"). in /xxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php:334 Stack trace: #0 /xxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php(420): Symfony\Component\Yaml\Inline::parseScalar('[setForumUserSe...', 2816, Array, 63, true, Array) #1 /xxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php(412): Symfony\Component\Yaml\Inline::parseSequence('[setForumUserSe...', 2816, 63, Array) #2 /xxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/Yaml/Inline.php(101): Symfony\Component\Yaml\Inline::parseSequence('[setForumUserSe...', 2816, 63, Array) #3 /xxxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/s in /xxxxx/zikula.wpzweinull.ch/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/YamlFileLoader.php on line 611
```

In the master branch I had when calling the settings in Dizkus again Error 500.

I have already reinstalled Zikula and deleted everything from the FTP account.

Can you please fix the above error again.

Thank you, I know that time costs, so I have a lot of patience.

**Comment by Kaik** [comment]
Oh 2.0 sorry I have not tested it on 2.0 yet only 1.5 I will do that soon today or tomorrow.

**Comment by Kaik** [comment]
Hi, please try master and for core 20 use the only master (v6 in the future) do not use v5 because it is for Core 1.5 only.

**Comment by AlexL777** [comment]
Hi,

it has now tried with the master branch. Settings can be accessed successfully, but the Dizkus options can not be saved. The page will no longer reload with the save.

And I can not create or delete new forums. Also 500 Error.

You can see this again.

Thank you for your help.

**Comment by Kaik** [comment]
Hi, I will be checking and fixing whole admin/user interface and functions this week and probably next as well. Now since InterCom is mostly ready for the first release I can focus back on Dizkus.
I need to review upgrade import and be sure that no data is missing now I'm not. I will close this ticket now and move mentioned errors to release task list #299  Thanks for reporting. I will be informing what is happening and when Dizkus will be ready for testing.

**Comment by AlexL777** [comment]
Ok, @Kaik ,

Thank you for taking the time to do so, and I am proving as much patience as before.

**Comment by Kaik** [comment]
Hi, again so I have checked on v5 and add works but it loads all users for moderators select which can end up as time out err or something like that. I will do more tests and will rewrite add/edit forum action anyway hopefully soon.

**Comment by AlexL777** [comment]
Good thank you. Then I wait for the first time until your tests are finished.
